new_comment:
    path: /new
    defaults: { _controller: "AppBundle:Comment:newComment" }
    methods: POST

delete_comment:
    path: /delete/{id}
    defaults: { _controller: "AppBundle:Comment:deleteComment" , id:null }
    methods: POST

list_comment:
    path: /list/{id}
    defaults: { _controller: "AppBundle:Comment:listComment" , id:null }
    methods: GET