default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: POST

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST