create_user:
    path: /create
    defaults: { _controller: "AppBundle:User:createUser" }
    methods: POST

update_user:
    path: /update
    defaults: { _controller: "AppBundle:User:updateUser" }
    methods: POST

upload_user:
    path: /upload
    defaults: { _controller: "AppBundle:User:upload" }
    methods: POST

channel_user:
    path: /channel/{identifier}
    defaults: { _controller: "AppBundle:User:channel", identifier:null }
    methods: GET