BackendBundle\Entity\Video:
    type: entity
    table: mv_video
    indexes:
        video_user_fk:
            columns:
                - user
    uniqueConstraints:
        video_uniques_fields:
            columns:
                - video_identifier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        videoIdentifier:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: video_identifier
        title:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        videoSource:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: video_source
        videoImage:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: video_image
        status:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
